"""add page_no to citations

Revision ID: 9765d2511d76
Revises: 08ee98e23d4c
Create Date: 2026-07-17 11:47:44.162483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9765d2511d76'
down_revision: Union[str, None] = '08ee98e23d4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('citations', sa.Column('page_no', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('citations', 'page_no')
    # ### end Alembic commands ###
